UpdateAppointmentInput:
  type: input-object
  config:
    fields:
      id:
        type: "Identifier!"
#      doctorId:
#        type: "Identifier"
      start:
        type: "DateTime"
      stop:
        type: "DateTime"
#      services:
#        type: "[Identifier!]"
