Query:
  type: object
  config:
    fields:
      clinics:
        type: "[Clinic!]!"
        description: "Read list of all clinics"
        resolve: "@=resolver('clinics')"

      clinic:
        type: "Clinic!"
        description: "Read particular clinic"
        args:
          id:
            type: "Identifier!"
        resolve: "@=resolver('clinic', [args['id']])"

      doctors:
        type: "[Doctor!]!"
        description: "Read list of all doctors"
        args:
          clinicId:
            type: "Identifier!"
        resolve: "@=resolver('doctors', [args['clinicId']])"

      doctor:
        type: "Doctor!"
        description: "Read particular doctor"
        args:
          id:
            type: "Identifier!"
        resolve: "@=resolver('doctor', [args['id']])"

      clients:
        type: "[Client!]!"
        description: "Read list of all clients"
        args:
          clinicId:
            type: "Identifier!"
        resolve: "@=resolver('clients', [args['clinicId']])"

      client:
        type: "Client!"
        description: "Read particular client"
        args:
          id:
            type: "Identifier!"
        resolve: "@=resolver('client', [args['id']])"

      appointments:
        type: "[Appointment!]!"
        description: "Read list of all appointments"
        args:
          filter:
            type: "AppointmentsFilter!"
        resolve: "@=resolver('appointments', [args['filter']])"

      appointment:
        type: "Appointment!"
        description: "Read particular appointment"
        args:
          id:
            type: "Identifier!"
        resolve: "@=resolver('appointment', [args['id']])"

      services:
        type: "[Service!]!"
        description: "Read list of all services"
        resolve: "@=resolver('services')"

      service:
        type: "Service!"
        description: "Read particular service"
        args:
          id:
            type: "Identifier!"
        resolve: "@=resolver('clinic', [args['id']])"
