AppointmentsFilter:
  type: input-object
  config:
    fields:
      clinicId:
        type: "Identifier!"
      clientId:
        type: "Identifier"
      doctorId:
        type: "Identifier"
      start:
        type: "DateTime!"
      stop:
        type: "DateTime!"
